### ISSUE TITLE
Question regarding syntax in Indexable

### ISSUE THREAD

**Issue by bbarker** [agocorona/TCache#6]
In the documentation there is the following example snippet:

```haskell
instance Indexable Data where
        key   User{uid=id}= id
        key   Item{iid=id}= id
```

I'm not sure what is going on with the `key   User{uid=id}= id` syntax. For instance, where is `key` defined (in TCache?) and what iare both uses of `id` doing here, exactly? 

Sorry if this is just a result of me being new to Haskell, and let me know if I can or should ask such questions elsewhere.

**Comment by bbarker** [comment]
So to answer this  it looks like key is defined here: https://hackage.haskell.org/package/TCache-0.12.1/docs/Data-TCache-Defs.html#t:Indexable  ... I get it now, more or less

**Comment by agocorona** [comment]
@bbarker:

No!  id is not the `id` of prelude. In this case  it is a variable which represent a field value

indexable and serializable are two classes that are used to define the IResource class. Since serializable can be general for many different records, one instance is enough for all of them, so a particular register need only his particular Indexable instance.    It is more convenient than IResource in many cases.
